### PR TITLE
Compile both `aarch64-postgres-linux-gnu` and `x86_64-postgres-linux-gnu` in `run` script

### PR DESCRIPTION
**Pull request by thomcc**
This is probably not ideal -- For this to succeed, you need to set something like

```sh
# if on x86_64
CARGO_TARGET_AARCH64_POSTGRES_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc \
	./run <cmd>

# if on aarch64
CARGO_TARGET_X86_64_POSTGRES_LINUX_GNU_LINKER=x86_64-linux-gnu-gcc \
	./run <cmd>
```

Because cargo can't link us for the non-host architecture (even if we used a linker capable of cross compilation it needs to know where the cross glibc is).

I'm going to make this a bit more automatic later on this weekend (so that it doesn't try to cross compile if it clearly won't work), but... it does get rather complex for a shell script. Would really love to do it in something better.

Do we care about users aside from plrust at all (aside from local testing)? Some of this would be easier to manage from inside there.

### CODE REVIEW

**Comment by thomcc** [comment]
Converted to draft becuase I'll be changing it a bit more.

**Comment by workingjubilee** [comment]
> Do we care about users aside from plrust at all (aside from local testing)? Some of this would be easier to manage from inside there.

Essentially no.

**Review by workingjubilee — COMMENTED** [review]
> I'm going to make this a bit more automatic later on this weekend (so that it doesn't try to cross compile if it clearly won't work), but... it does get rather complex for a shell script. Would really love to do it in something better.

There's not necessarily any reason to continue to use a shell script here if it has exceeded the complexity bound that is reasonable for shell scripts.

**Comment by thomcc** [comment]
> Converted to draft becuase I'll be changing it a bit more.

This will probably have to happen later.

**Review by eeeebbbbrrrr — APPROVED** [review]
I approve.  I've basically run this about 3 dozen times locally and it does what it should.

**Pull request merged**
